name: <your_env_name>
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - click
  - jupyter
  - jedi
  - ipykernel
  - dill
  - pytest
  - pip
  - nb_conda
  - pip:
    - jupyternotify
